<?php

    return [
        'genders' => [
            ['label' => 'Male', 'value' => 'male'],
            ['label' => 'Female', 'value' => 'female'],
        ],
        'statuses' => [
            ['label' => 'Active', 'value' => 1],
            ['label' => 'Inactive', 'value' => 0],
        ],
        'service_statuses'=>[
            ['label' => 'Request by Customer', 'value' => 1],
            ['label' => 'Pending', 'value' => 2],
            ['label' => 'Payment Confirmed', 'value' => 3],
            ['label' => 'Reject', 'value' => 4],
            ['label' => 'Documents Submitted', 'value' => 5],
            ['label' => 'In Progress', 'value' => 6],
            ['label' => 'Approved', 'value' => 7],
            ['label' => 'Dispatched to Customer', 'value' => 8],
            ['label' => 'Completed', 'value' => 9],
        ],
        'states' => [
            ['label' => '1','label_mm'=>'', 'value' => '1'],
            ['label' => '2','label_mm'=>'', 'value' => '2'],
            ['label' => '3','label_mm'=>'', 'value' => '3'],
            ['label' => '4','label_mm'=>'', 'value' => '4'],
            ['label' => '5','label_mm'=>'', 'value' => '5'],
            ['label' => '6','label_mm'=>'', 'value' => '6'],
            ['label' => '7','label_mm'=>'', 'value' => '7'],
            ['label' => '8','label_mm'=>'', 'value' => '8'],
            ['label' => '9','label_mm'=>'', 'value' => '9'],
            ['label' => '10','label_mm'=>'', 'value' => '10'],
            ['label' => '11','label_mm'=>'', 'value' => '11'],
            ['label' => '12','label_mm'=>'', 'value' => '12'],
            ['label' => '13','label_mm'=>'', 'value' => '13'],
            ['label' => '14','label_mm'=>'', 'value' => '14'],
            ['label' => '9*','label_mm'=>'', 'value' => '9*'],
        ],
        'townships' => [
            '1' => [
                ['label' => 'HAPANA', 'label_mm' => 'ဟပန', 'value' => 'HAPANA'],
                ['label' => 'KAPATA', 'label_mm' => 'ကပတ', 'value' => 'KAPATA'],
                ['label' => 'KHABADA', 'label_mm' => 'ခဘဒ', 'value' => 'KHABADA'],
                ['label' => 'PHAKANA', 'label_mm' => 'ဖကန', 'value' => 'PHAKANA'],
                ['label' => 'MAKHABA', 'label_mm' => 'မခဘ', 'value' => 'MAKHABA'],
                ['label' => 'DAPHAYA', 'label_mm' => 'ဒဖယ', 'value' => 'DAPHAYA'],
                ['label' => 'PAWANA', 'label_mm' => 'ပ၀န', 'value' => 'PAWANA'],
                ['label' => 'PANADA', 'label_mm' => 'ပနဒ', 'value' => 'PANADA'],
                ['label' => 'SADANA', 'label_mm' => 'ဆဒန', 'value' => 'SADANA'],
                ['label' => 'BAMANA', 'label_mm' => 'ဗမန', 'value' => 'BAMANA'],
                ['label' => 'KAMANA', 'label_mm' => 'ဖကန', 'value' => 'KAMANA'],
                ['label' => 'MASANA', 'label_mm' => 'မစန', 'value' => 'MASANA'],
                ['label' => 'LAGANA', 'label_mm' => 'လဂန', 'value' => 'LAGANA'],
                ['label' => 'NAMANA', 'label_mm' => 'နမန', 'value' => 'NAMANA'],
                ['label' => 'MAMANA', 'label_mm' => 'မမန', 'value' => 'MAMANA'],
                ['label' => 'KAMATA', 'label_mm' => 'ကမန', 'value' => 'KAMATA'],
                ['label' => 'MAKATA', 'label_mm' => 'မကတ', 'value' => 'MAKATA'],
                ['label' => 'MANYANA', 'label_mm' => 'မညန', 'value' => 'MANYANA'],
                ['label' => 'KHAPHANA', 'label_mm' => 'ခဖန', 'value' => 'KHAPHANA'],
                ['label' => 'SABATA', 'label_mm' => 'ဆဘန', 'value' => 'SABATA'],
                ['label' => 'SALANA', 'label_mm' => 'ဆလန', 'value' => 'SALANA'],
                ['label' => 'AHGAYA', 'label_mm' => 'အဂယ', 'value' => 'AHGAYA'],
                ['label' => 'MAKANA', 'label_mm' => 'မကန', 'value' => 'MAKANA'],
                ['label' => 'YABAYA', 'label_mm' => 'ရဘယ', 'value' => 'YABAYA'],
                ['label' => 'TANANA', 'label_mm' => 'တနန', 'value' => 'TANANA'],
                ['label' => 'KHALAPHA', 'label_mm' => 'ခလဖ', 'value' => 'KHALAPHA'],
                ['label' => 'PATAAH', 'label_mm' => 'ပတအ', 'value' => 'PATAAH'],
                ['label' => 'SAPABA', 'label_mm' => 'ဆပဘ', 'value' => 'SAPABA'],
                ['label' => 'YAKANA', 'label_mm' => 'ရကန', 'value' => 'YAKANA'],
                ['label' => 'WAMANA', 'label_mm' => '၀မန', 'value' => 'WAMANA'],
                ['label' => 'MALANA', 'label_mm' => 'မလန', 'value' => 'MALANA'],
            ],

            '2' => [
                ['label' => 'PHASANA', 'label_mm' => 'ဖဆန', 'value' => 'PHASANA'],
                ['label' => 'PHAYASA', 'label_mm' => 'ဖရဆ', 'value' => 'PHAYASA'],
                ['label' => 'BALAKHA', 'label_mm' => 'ဘလခ', 'value' => 'BALAKHA'],
                ['label' => 'MASANA',  'label_mm' => 'မစန',  'value' => 'MASANA'],
                ['label' => 'YATHANA', 'label_mm' => 'ရသန', 'value' => 'YATHANA'],
                ['label' => 'LAKANA',  'label_mm' => 'လကန',  'value' => 'LAKANA'],
                ['label' => 'YATANA',  'label_mm' => 'ရတန',  'value' => 'YATANA'],
                ['label' => 'DAMASA',  'label_mm' => 'ဒမဆ',  'value' => 'DAMASA'],
            ],

            '3' => [
                ['label' => 'BAKALA', 'label_mm' => 'ဘကလ', 'value' => 'BAKALA'],
                ['label' => 'THATAKA', 'label_mm' => 'သတက', 'value' => 'THATAKA'],
                ['label' => 'SAKALA', 'label_mm' => 'စကလ', 'value' => 'SAKALA'],
                ['label' => 'WALAMA', 'label_mm' => '၀လမ', 'value' => 'WALAMA'],
                ['label' => 'BAGALA', 'label_mm' => 'ဘဂလ', 'value' => 'BAGALA'],
                ['label' => 'KAKAYA', 'label_mm' => 'ကကရ', 'value' => 'KAKAYA'],
                ['label' => 'PAKANA', 'label_mm' => 'ပကန', 'value' => 'PAKANA'],
                ['label' => 'LABANA', 'label_mm' => 'လဘန', 'value' => 'LABANA'],
                ['label' => 'BAAHNA', 'label_mm' => 'ဘအန', 'value' => 'BAAHNA'],
                ['label' => 'LATHANA', 'label_mm' => 'လသန', 'value' => 'LATHANA'],
                ['label' => 'YAYATHA', 'label_mm' => 'ရရသ', 'value' => 'YAYATHA'],
                ['label' => 'KADANA', 'label_mm' => 'ကဒန', 'value' => 'KADANA'],
                ['label' => 'KASAKA', 'label_mm' => 'ကဆက', 'value' => 'KASAKA'],
                ['label' => 'THATANA', 'label_mm' => 'သတန', 'value' => 'THATANA'],
                ['label' => 'BATHASA', 'label_mm' => 'ဘသဆ', 'value' => 'BATHASA'],
                ['label' => 'MAWATA',  'label_mm' => 'မဝတ', 'value' => 'MAWATA'],
                ['label' => 'KAMAMA',  'label_mm' => 'ကမမ', 'value' => 'KAMAMA'],
                ['label' => 'PHAPANA', 'label_mm' => 'ဖပန', 'value' => 'PHAPANA'],
            ],

            '4' => [
                ['label' => 'PALAWA', 'label_mm' => 'ပလဝ', 'value' => 'PALAWA'],
                ['label' => 'KAKHANA', 'label_mm' => 'ကခန', 'value' => 'KAKHANA'],
                ['label' => 'PHALANA', 'label_mm' => 'ဖလန', 'value' => 'PHALANA'],
                ['label' => 'TATANA',  'label_mm' => 'တတန',  'value' => 'TATANA'],
                ['label' => 'TAZANA',  'label_mm' => 'တဇန',  'value' => 'TAZANA'],
                ['label' => 'MATAPA',  'label_mm' => 'မတပ',  'value' => 'MATAPA'],
                ['label' => 'MATANA',  'label_mm' => 'မတန',  'value' => 'MATANA'],
                ['label' => 'SAMANA',  'label_mm' => 'ဆမန',  'value' => 'SAMANA'],
                ['label' => 'KAPALA',  'label_mm' => 'ကပလ',  'value' => 'KAPALA'],
                ['label' => 'YAKHADA', 'label_mm' => 'ရခဒ',  'value' => 'YAKHADA'],
                ['label' => 'HAKHANA', 'label_mm' => 'ဟခန',  'value' => 'HAKHANA'],
                ['label' => 'HTATALA', 'label_mm' => 'ထတလ',  'value' => 'HTATALA'],
                ['label' => 'YAZANA',  'label_mm' => 'ရဇန',  'value' => 'YAZANA'],
            ],

           '5' => [
                ['label' => 'PALABA', 'label_mm' => 'ပလဘ', 'value' => 'PALABA'],
                ['label' => 'PASANA', 'label_mm' => 'ပဆန', 'value' => 'PASANA'],
                ['label' => 'AHYATA', 'label_mm' => 'အရတ', 'value' => 'AHYATA'],
                ['label' => 'KHAPANA', 'label_mm' => 'ခပန', 'value' => 'KHAPANA'],
                ['label' => 'KAMANA', 'label_mm' => 'ကမန', 'value' => 'KAMANA'],
                ['label' => 'MATHANA', 'label_mm' => 'မသန', 'value' => 'MATHANA'],
                ['label' => 'HAMALA', 'label_mm' => 'ဟမလ', 'value' => 'HAMALA'],
                ['label' => 'BAMANA', 'label_mm' => 'ဗမန', 'value' => 'BAMANA'],
                ['label' => 'MAMANA', 'label_mm' => 'မမန', 'value' => 'MAMANA'],
                ['label' => 'SALAKA', 'label_mm' => 'ဆလက', 'value' => 'SALAKA'],
                ['label' => 'NGAZANA', 'label_mm' => 'ငဇန', 'value' => 'NGAZANA'],
                ['label' => 'YAOUNA', 'label_mm' => 'ရဥန', 'value' => 'YAOUNA'],
                ['label' => 'KALAHTA', 'label_mm' => 'ကလထ', 'value' => 'KALAHTA'],
                ['label' => 'YATHAKA', 'label_mm' => 'ရသက', 'value' => 'YATHAKA'],
                ['label' => 'HSAMARA', 'label_mm' => 'ဆမရ', 'value' => 'HSAMARA'],
                ['label' => 'SAKANA', 'label_mm' => 'စကန', 'value' => 'SAKANA'],
                ['label' => 'MALANA', 'label_mm' => 'မလန', 'value' => 'MALANA'],
                ['label' => 'YAMAPA', 'label_mm' => 'ယမပ', 'value' => 'YAMAPA'],
                ['label' => 'KALATA', 'label_mm' => 'ကလတ', 'value' => 'KALATA'],
                ['label' => 'KALANA', 'label_mm' => 'ကလန', 'value' => 'KALANA'],
                ['label' => 'KHATANA', 'label_mm' => 'ခတန', 'value' => 'KHATANA'],
                ['label' => 'HTAPAKHA', 'label_mm' => 'ထပခ', 'value' => 'HTAPAKHA'],
                ['label' => 'LAHANA', 'label_mm' => 'လဟန', 'value' => 'LAHANA'],
                ['label' => 'LAYANA', 'label_mm' => 'လရန', 'value' => 'LAYANA'],
                ['label' => 'NAYANA', 'label_mm' => 'နယန', 'value' => 'NAYANA'],
                ['label' => 'KALAWA', 'label_mm' => 'ကလ၀', 'value' => 'KALAWA'],
                ['label' => 'MAKANA', 'label_mm' => 'မကန', 'value' => 'MAKANA'],
                ['label' => 'HTAKHANA', 'label_mm' => 'ထခန', 'value' => 'HTAKHANA'],
                ['label' => 'AHTANA', 'label_mm' => 'အတန', 'value' => 'AHTANA'],
                ['label' => 'KATHANA', 'label_mm' => 'ကသန', 'value' => 'KATHANA'],
                ['label' => 'WATHANA', 'label_mm' => 'ဝသန', 'value' => 'WATHANA'],
                ['label' => 'PHAPANA', 'label_mm' => 'ဖပန', 'value' => 'PHAPANA'],
                ['label' => 'KHAOUTA', 'label_mm' => 'ခဥတ', 'value' => 'KHAOUTA'],
                ['label' => 'MAYANA', 'label_mm' => 'မရန', 'value' => 'MAYANA'],
                ['label' => 'DAPAYA', 'label_mm' => 'ဒပယ', 'value' => 'DAPAYA'],
                ['label' => 'KABALA', 'label_mm' => 'ကဘလ', 'value' => 'KABALA'],
                ['label' => 'KHAOUNA', 'label_mm' => 'ခဥန', 'value' => 'KHAOUNA'],
                ['label' => 'YABANA', 'label_mm' => 'ရဘန', 'value' => 'YABANA'],
                ['label' => 'TASANA', 'label_mm' => 'တဆန', 'value' => 'TASANA'],
                ['label' => 'WALANA', 'label_mm' => 'ဝလန', 'value' => 'WALANA'],
                ['label' => 'BATALA', 'label_mm' => 'ဘတလ', 'value' => 'BATALA'],
                ['label' => 'TAMANA', 'label_mm' => 'တမန', 'value' => 'TAMANA'],
                ['label' => 'KANANA', 'label_mm' => 'ကနန', 'value' => 'KANANA'],
                ['label' => 'PALANA', 'label_mm' => 'ပလန', 'value' => 'PALANA'],
                ['label' => 'MAPALA', 'label_mm' => 'မပလ', 'value' => 'MAPALA'],
                ['label' => 'MAMATA', 'label_mm' => 'မမတ', 'value' => 'MAMATA'],
                ['label' => 'DAHANA', 'label_mm' => 'ဒဟန', 'value' => 'DAHANA'],
            ],

            '6' => [
                ['label' => 'KASANA', 'label_mm' => 'ကစန', 'value' => 'KASANA'],
                ['label' => 'MAMANA', 'label_mm' => 'မမန', 'value' => 'MAMANA'],
                ['label' => 'MAAHYA', 'label_mm' => 'မအရ', 'value' => 'MAAHYA'],
                ['label' => 'TANATHA', 'label_mm' => 'တနသ', 'value' => 'TANATHA'],
                ['label' => 'PAKAMA', 'label_mm' => 'ပကမ', 'value' => 'PAKAMA'],
                ['label' => 'PALATA', 'label_mm' => 'ပလတ', 'value' => 'PALATA'],
                ['label' => 'YAPHANA', 'label_mm' => 'ရဖန', 'value' => 'YAPHANA'],
                ['label' => 'KATHANA', 'label_mm' => 'ကသန', 'value' => 'KATHANA'],
                ['label' => 'TATHAYA', 'label_mm' => 'တသရ', 'value' => 'TATHAYA'],
                ['label' => 'NGAYAKA', 'label_mm' => 'ငရက', 'value' => 'NGAYAKA'],
                ['label' => 'MAAHNA', 'label_mm' => 'မအန', 'value' => 'MAAHNA'],
                ['label' => 'KAYAYA', 'label_mm' => 'ကရရ', 'value' => 'KAYAYA'],
                ['label' => 'LALANA', 'label_mm' => 'လလန', 'value' => 'LALANA'],
                ['label' => 'PALANA', 'label_mm' => 'ပလန', 'value' => 'PALANA'],
                ['label' => 'KHAMAKA', 'label_mm' => 'ခမက', 'value' => 'KHAMAKA'],
                ['label' => 'HTAWANA', 'label_mm' => 'ထဝန', 'value' => 'HTAWANA'],
                ['label' => 'KALAAH', 'label_mm' => 'ကလအ', 'value' => 'KALAAH'],
                ['label' => 'MATANA', 'label_mm' => 'မတန', 'value' => 'MATANA'],
                ['label' => 'THAYAKHA', 'label_mm' => 'သရခ', 'value' => 'THAYAKHA'],
                ['label' => 'BAPANA', 'label_mm' => 'ဘပန', 'value' => 'BAPANA'],
            ],

            '7' => [
                ['label' => 'YAKANA', 'label_mm' => 'ရကန', 'value' => 'YAKANA'],
                ['label' => 'KAWANA', 'label_mm' => 'ကဝန', 'value' => 'KAWANA'],
                ['label' => 'PATATA', 'label_mm' => 'ပတတ', 'value' => 'PATATA'],
                ['label' => 'KAKANA', 'label_mm' => 'ကကန', 'value' => 'KAKANA'],
                ['label' => 'MALANA', 'label_mm' => 'မလန', 'value' => 'MALANA'],
                ['label' => 'DAOUNA', 'label_mm' => 'ဒဥန', 'value' => 'DAOUNA'],
                ['label' => 'KATAKHA', 'label_mm' => 'ကတခ', 'value' => 'KATAKHA'],
                ['label' => 'THANAPA', 'label_mm' => 'သနပ', 'value' => 'THANAPA'],
                ['label' => 'WAMANA', 'label_mm' => 'ဝမန', 'value' => 'WAMANA'],
                ['label' => 'PATANA', 'label_mm' => 'ပတန', 'value' => 'PATANA'],
                ['label' => 'YATANA', 'label_mm' => 'ရတန', 'value' => 'YATANA'],
                ['label' => 'KAPAKA', 'label_mm' => 'ကပက', 'value' => 'KAPAKA'],
                ['label' => 'MANYANA', 'label_mm' => 'မညန', 'value' => 'MANYANA'],
                ['label' => 'ZAKANA', 'label_mm' => 'ဇကန', 'value' => 'ZAKANA'],
                ['label' => 'HTATAPA', 'label_mm' => 'ထတပ', 'value' => 'HTATAPA'],
                ['label' => 'PHAMANA', 'label_mm' => 'ဖမန', 'value' => 'PHAMANA'],
                ['label' => 'TANGANA', 'label_mm' => 'တငန', 'value' => 'TANGANA'],
                ['label' => 'YATAYA', 'label_mm' => 'ရတရ', 'value' => 'YATAYA'],
                ['label' => 'LAPATA', 'label_mm' => 'လပတ', 'value' => 'LAPATA'],
                ['label' => 'AHPHANA', 'label_mm' => 'အဖန', 'value' => 'AHPHANA'],
                ['label' => 'THAKANA', 'label_mm' => 'သကန', 'value' => 'THAKANA'],
                ['label' => 'PAKHATA', 'label_mm' => 'ပခတ', 'value' => 'PAKHATA'],
                ['label' => 'AHPHANA', 'label_mm' => 'အဖန', 'value' => 'AHPHANA'],
                ['label' => 'THASANA', 'label_mm' => 'သဆန', 'value' => 'THASANA'],
                ['label' => 'KATATA', 'label_mm' => 'ကတတ', 'value' => 'KATATA'],
                ['label' => 'KAKANA', 'label_mm' => 'ကကန', 'value' => 'KAKANA'],
                ['label' => 'PAKHANA', 'label_mm' => 'ပခန', 'value' => 'PAKHANA'],
                ['label' => 'PAMANA', 'label_mm' => 'ပမန', 'value' => 'PAMANA'],
                ['label' => 'THAWATA', 'label_mm' => 'သဝတ', 'value' => 'THAWATA'],
                ['label' => 'NYALAPA', 'label_mm' => 'ညလပ', 'value' => 'NYALAPA'],
                ['label' => 'AHTANA', 'label_mm' => 'အတန', 'value' => 'AHTANA'],
                ['label' => 'NATALA', 'label_mm' => 'နတလ', 'value' => 'NATALA'],
                ['label' => 'PATASA', 'label_mm' => 'ပတဆ', 'value' => 'PATASA'],
                ['label' => 'MADANA', 'label_mm' => 'မဒန', 'value' => 'MADANA'],
                ['label' => 'PANAKA', 'label_mm' => 'ပနက', 'value' => 'PANAKA'],
                ['label' => 'PATALA', 'label_mm' => 'ပတလ', 'value' => 'PATALA'],
            ],

            '8' => [
                ['label' => 'MABANA', 'label_mm' => 'မဘန', 'value' => 'MABANA'],
                ['label' => 'NGAPHANA', 'label_mm' => 'ငဖန', 'value' => 'NGAPHANA'],
                ['label' => 'PAPHANA', 'label_mm' => 'ပဖန', 'value' => 'PAPHANA'],
                ['label' => 'SAKANA', 'label_mm' => 'စကန', 'value' => 'SAKANA'],
                ['label' => 'SALANA', 'label_mm' => 'စလန', 'value' => 'SALANA'],
                ['label' => 'MAMANA', 'label_mm' => 'မမန', 'value' => 'MAMANA'],
                ['label' => 'PAMANA', 'label_mm' => 'ပမန', 'value' => 'PAMANA'],
                ['label' => 'YASAKA', 'label_mm' => 'ရစက', 'value' => 'YASAKA'],
                ['label' => 'KAMANA', 'label_mm' => 'ကမန', 'value' => 'KAMANA'],
                ['label' => 'MALANA', 'label_mm' => 'မလန', 'value' => 'MALANA'],
                ['label' => 'THAYANA', 'label_mm' => 'သရန', 'value' => 'THAYANA'],
                ['label' => 'SAPAWA', 'label_mm' => 'ဆပ၀', 'value' => 'SAPAWA'],
                ['label' => 'SAMANA', 'label_mm' => 'ဆမန', 'value' => 'SAMANA'],
                ['label' => 'MATANA', 'label_mm' => 'မတန', 'value' => 'MATANA'],
                ['label' => 'TATAKA', 'label_mm' => 'တတက', 'value' => 'TATAKA'],
                ['label' => 'HTALANA', 'label_mm' => 'ထလန', 'value' => 'HTALANA'],
                ['label' => 'KHAMANA', 'label_mm' => 'ခမန', 'value' => 'KHAMANA'],
                ['label' => 'MAHTANA', 'label_mm' => 'မထန', 'value' => 'MAHTANA'],
                ['label' => 'AHLANA', 'label_mm' => 'အလန', 'value' => 'AHLANA'],
                ['label' => 'MATHANA', 'label_mm' => 'မသန', 'value' => 'MATHANA'],
                ['label' => 'PAKHAKA', 'label_mm' => 'ပခက', 'value' => 'PAKHAKA'],
                ['label' => 'MAKANA', 'label_mm' => 'မကန', 'value' => 'MAKANA'],
                ['label' => 'SAPHANA', 'label_mm' => 'ဆဖန', 'value' => 'SAPHANA'],
                ['label' => 'SATAYA', 'label_mm' => 'စတရ', 'value' => 'SATAYA'],
                ['label' => 'YANAKHA', 'label_mm' => 'ရနခ', 'value' => 'YANAKHA'],
                ['label' => 'GAGANA', 'label_mm' => 'ဂဂန', 'value' => 'GAGANA'],
                ['label' => 'KAHTANA', 'label_mm' => 'ကထန', 'value' => 'KAHTANA'],
                ['label' => 'YAMANA', 'label_mm' => 'ယမန', 'value' => 'YAMANA'],
                ['label' => 'NAMANA', 'label_mm' => 'နမန', 'value' => 'NAMANA'],
            ],

            '9' => [
                ['label' => 'KASANA', 'label_mm' => 'ကဆန', 'value' => 'KASANA'],
                ['label' => 'MATHANA', 'label_mm' => 'မသန', 'value' => 'MATHANA'],
                ['label' => 'AHMAZA', 'label_mm' => 'အမဇ', 'value' => 'AHMAZA'],
                ['label' => 'KHAMASA', 'label_mm' => 'ခမစ', 'value' => 'KHAMASA'],
                ['label' => 'MAHAMA', 'label_mm' => 'မဟမ', 'value' => 'MAHAMA'],
                ['label' => 'ZABATHA', 'label_mm' => 'ဇဗသ', 'value' => 'ZABATHA'],
                ['label' => 'KAPATA', 'label_mm' => 'ကပတ', 'value' => 'KAPATA'],
                ['label' => 'PATHAKA', 'label_mm' => 'ပသက', 'value' => 'PATHAKA'],
                ['label' => 'TATAOU', 'label_mm' => 'တတဥ', 'value' => 'TATAOU'],
                ['label' => 'SAKATA', 'label_mm' => 'စကတ', 'value' => 'SAKATA'],
                ['label' => 'SAKANA', 'label_mm' => 'စကန', 'value' => 'SAKANA'],
                ['label' => 'AUTATHA', 'label_mm' => 'ဥတသ', 'value' => 'AUTATHA'],
                ['label' => 'PABATHA', 'label_mm' => 'ပဗသ', 'value' => 'PABATHA'],
                ['label' => 'KAMANA', 'label_mm' => 'ကမန', 'value' => 'KAMANA'],
                ['label' => 'MAMANA', 'label_mm' => 'မမန', 'value' => 'MAMANA'],
                ['label' => 'MAYAMA', 'label_mm' => 'မရမ', 'value' => 'MAYAMA'],
                ['label' => 'AHMAYA', 'label_mm' => 'အမရ', 'value' => 'AHMAYA'],
                ['label' => 'NAHTAKA', 'label_mm' => 'နထက', 'value' => 'NAHTAKA'],
                ['label' => 'MANAMA', 'label_mm' => 'မနမ', 'value' => 'MANAMA'],
                ['label' => 'MANATA', 'label_mm' => 'မနတ', 'value' => 'MANATA'],
                ['label' => 'MAYATA', 'label_mm' => 'မရတ', 'value' => 'MAYATA'],
                ['label' => 'TAKANA', 'label_mm' => 'တကန', 'value' => 'TAKANA'],
                ['label' => 'NYAOUNA', 'label_mm' => 'ညဥန', 'value' => 'NYAOUNA'],
                ['label' => 'MAHTALA', 'label_mm' => 'မထလ', 'value' => 'MAHTALA'],
                ['label' => 'WATANA', 'label_mm' => 'ဝတန', 'value' => 'WATANA'],
                ['label' => 'TAKATA', 'label_mm' => 'တကတ', 'value' => 'TAKATA'],
                ['label' => 'PAKAKHA', 'label_mm' => 'ပကခ', 'value' => 'PAKAKHA'],
                ['label' => 'THASANA', 'label_mm' => 'သစန', 'value' => 'THASANA'],
                ['label' => 'MAKHANA', 'label_mm' => 'မခန', 'value' => 'MAKHANA'],
                ['label' => 'NGAZANA', 'label_mm' => 'ငဇန', 'value' => 'NGAZANA'],
                ['label' => 'NGATHAYA', 'label_mm' => 'ငသရ', 'value' => 'NGATHAYA'],
                ['label' => 'MAKANA', 'label_mm' => 'မကန', 'value' => 'MAKANA'],
                ['label' => 'PAOULA', 'label_mm' => 'ပဥလ', 'value' => 'PAOULA'],
                ['label' => 'THAPAKA', 'label_mm' => 'သပက', 'value' => 'THAPAKA'],
                ['label' => 'PABANA', 'label_mm' => 'ပဘန', 'value' => 'PABANA'],
                ['label' => 'YAMATHA', 'label_mm' => 'ရမသ', 'value' => 'YAMATHA'],
                ['label' => 'DAKHATHA', 'label_mm' => 'ဒခသ', 'value' => 'DAKHATHA'],
                ['label' => 'LAWANA', 'label_mm' => 'လဝန', 'value' => 'LAWANA'],
                ['label' => 'PAMANA', 'label_mm' => 'ပမန', 'value' => 'PAMANA'],
                ['label' => 'ZAYATHA', 'label_mm' => 'ဇယသ', 'value' => 'ZAYATHA'],
                ['label' => 'MATAYA', 'label_mm' => 'မတရ', 'value' => 'MATAYA'],
                ['label' => 'TATHANA', 'label_mm' => 'တသန', 'value' => 'TATHANA'],
                ['label' => 'MALANA', 'label_mm' => 'မလန', 'value' => 'MALANA'],
                ['label' => 'KHAAHZA', 'label_mm' => 'ခအဇ', 'value' => 'KHAAHZA'],
               // ['label' => 'BAGAN', 'label_mm' => 'ပုဂံ', 'value' => 'BAGAN'],
                ['label' => 'YAKANA', 'label_mm' => 'ရကန', 'value' => 'YAKANA'],
            ],

            '10' => [
                ['label' => 'BALANA', 'label_mm' => 'ဘလန', 'value' => 'BALANA'],
                ['label' => 'PAMANA', 'label_mm' => 'ပမန', 'value' => 'PAMANA'],
                ['label' => 'YAMANA', 'label_mm' => 'ရမန', 'value' => 'YAMANA'],
                ['label' => 'KAKHAMA', 'label_mm' => 'ကခမ', 'value' => 'KAKHAMA'],
                ['label' => 'LAMANA', 'label_mm' => 'လမန', 'value' => 'LAMANA'],
                ['label' => 'KHASANA', 'label_mm' => 'ခဆန', 'value' => 'KHASANA'],
                ['label' => 'KAMAYA', 'label_mm' => 'ကမရ', 'value' => 'KAMAYA'],
                ['label' => 'MALAMA', 'label_mm' => 'မလမ', 'value' => 'MALAMA'],
                ['label' => 'MADANA', 'label_mm' => 'မဒန', 'value' => 'MADANA'],
                ['label' => 'THAPHAYA', 'label_mm' => 'သဖရ', 'value' => 'THAPHAYA'],
                ['label' => 'KAHTANA', 'label_mm' => 'ကထန', 'value' => 'KAHTANA'],
                ['label' => 'THAHTANA', 'label_mm' => 'သထန', 'value' => 'THAHTANA'],
                ['label' => 'KHAZANA', 'label_mm' => 'ခဇန', 'value' => 'KHAZANA'],
            ],

            '11' => [
                ['label' => 'GAMANA', 'label_mm' => 'ဂမန', 'value' => 'GAMANA'],
                ['label' => 'MAPATA', 'label_mm' => 'မပတ', 'value' => 'MAPATA'],
                ['label' => 'TAPAWA', 'label_mm' => 'တပ၀', 'value' => 'TAPAWA'],
                ['label' => 'THATANA', 'label_mm' => 'သတန', 'value' => 'THATANA'],
                ['label' => 'BATHATA', 'label_mm' => 'ဘသတ', 'value' => 'BATHATA'],
                ['label' => 'PANATA', 'label_mm' => 'ပဏတ', 'value' => 'PANATA'],
                ['label' => 'SATANA', 'label_mm' => 'စတန', 'value' => 'SATANA'],
                ['label' => 'KATALA', 'label_mm' => 'ကတလ', 'value' => 'KATALA'],
                ['label' => 'AHMANA', 'label_mm' => 'အမန', 'value' => 'AHMANA'],
                ['label' => 'KAPHANA', 'label_mm' => 'ကဖန', 'value' => 'KAPHANA'],
                ['label' => 'MAAHNA', 'label_mm' => 'မအန', 'value' => 'MAAHNA'],
                ['label' => 'YABANA', 'label_mm' => 'ရဗန', 'value' => 'YABANA'],
                ['label' => 'MATANA', 'label_mm' => 'မတန', 'value' => 'MATANA'],
                ['label' => 'MAPANA', 'label_mm' => 'မပန', 'value' => 'MAPANA'],
                ['label' => 'MAOUNA', 'label_mm' => 'မဥန', 'value' => 'MAOUNA'],
                ['label' => 'PATANA', 'label_mm' => 'ပတန', 'value' => 'PATANA'],
                ['label' => 'PANAKA', 'label_mm' => 'ပဏက', 'value' => 'PANAKA'],
                ['label' => 'YATHATA', 'label_mm' => 'ရသတ', 'value' => 'YATHATA'],
                ['label' => 'KATANA', 'label_mm' => 'ကတန', 'value' => 'KATANA'],
                ['label' => 'TAKANA', 'label_mm' => 'တကန', 'value' => 'TAKANA'],
                ['label' => 'MAAHTA', 'label_mm' => 'မအတ', 'value' => 'MAAHTA'],
            ],

            '12' => [
                ['label' => 'DAGAYA', 'label_mm' => 'ဒဂရ', 'value' => 'DAGAYA'],
                ['label' => 'DAPANA', 'label_mm' => 'ဒပန', 'value' => 'DAPANA'],
                ['label' => 'OUKATA', 'label_mm' => 'ဥကတ', 'value' => 'OUKATA'],
                ['label' => 'THAKATA', 'label_mm' => 'သကတ', 'value' => 'THAKATA'],
                ['label' => 'THAGAKA', 'label_mm' => 'သဃက', 'value' => 'THAGAKA'],
                ['label' => 'YAKANA', 'label_mm' => 'ရကန', 'value' => 'YAKANA'],
                ['label' => 'MABANA', 'label_mm' => 'မဘန', 'value' => 'MABANA'],
                ['label' => 'MAGADA', 'label_mm' => 'မဂဒ', 'value' => 'MAGADA'],
                ['label' => 'YAPATHA', 'label_mm' => 'ရပသ', 'value' => 'YAPATHA'],
                ['label' => 'TAKANA', 'label_mm' => 'တကန', 'value' => 'TAKANA'],
                ['label' => 'DALANA', 'label_mm' => 'ဒလန', 'value' => 'DALANA'],
                ['label' => 'KAKHAKA', 'label_mm' => 'ကခက', 'value' => 'KAKHAKA'],
                ['label' => 'THALANA', 'label_mm' => 'သလန', 'value' => 'THALANA'],
                ['label' => 'THAKHANA', 'label_mm' => 'သခန', 'value' => 'THAKHANA'],
                ['label' => 'TATANA', 'label_mm' => 'တတန', 'value' => 'TATANA'],
                ['label' => 'BAHANA', 'label_mm' => 'ဗဟန', 'value' => 'BAHANA'],
                ['label' => 'LAMANA', 'label_mm' => 'လမန', 'value' => 'LAMANA'],
                ['label' => 'KATATA', 'label_mm' => 'ကတတ', 'value' => 'KATATA'],
                ['label' => 'KAMATA', 'label_mm' => 'ကမတ', 'value' => 'KAMATA'],
                ['label' => 'LATHANA', 'label_mm' => 'လသန', 'value' => 'LATHANA'],
                ['label' => 'MAYAKA', 'label_mm' => 'မရက', 'value' => 'MAYAKA'],
                ['label' => 'HTATAPA', 'label_mm' => 'ထတပ', 'value' => 'HTATAPA'],
                ['label' => 'TAMANA', 'label_mm' => 'တမန', 'value' => 'TAMANA'],
                ['label' => 'LATHAYA', 'label_mm' => 'လသယ', 'value' => 'LATHAYA'],
                ['label' => 'SAKHANA', 'label_mm' => 'စခန', 'value' => 'SAKHANA'],
                ['label' => 'BATAHTA', 'label_mm' => 'ဗတထ', 'value' => 'BATAHTA'],
                ['label' => 'SAKAKHA', 'label_mm' => 'ဆကခ', 'value' => 'SAKAKHA'],
                ['label' => 'KAMAYA', 'label_mm' => 'ကမရ', 'value' => 'KAMAYA'],
                ['label' => 'KAKAKA', 'label_mm' => 'ကကက', 'value' => 'KAKAKA'],
                ['label' => 'DAGANA', 'label_mm' => 'ဒဂန', 'value' => 'DAGANA'],
                ['label' => 'MAGATA', 'label_mm' => 'မဂတ', 'value' => 'MAGATA'],
                ['label' => 'OUKAMA', 'label_mm' => 'ဥကမ', 'value' => 'OUKAMA'],
                ['label' => 'KHAYANA', 'label_mm' => 'ခရန', 'value' => 'KHAYANA'],
                ['label' => 'DAGATA', 'label_mm' => 'ဒဂတ', 'value' => 'DAGATA'],
                ['label' => 'DAGAMA', 'label_mm' => 'ဒဂမ', 'value' => 'DAGAMA'],
                ['label' => 'LAMATA', 'label_mm' => 'လမတ', 'value' => 'LAMATA'],
                ['label' => 'DAGASA', 'label_mm' => 'ဒဂဆ', 'value' => 'DAGASA'],
                ['label' => 'LAKANA', 'label_mm' => 'လကန', 'value' => 'LAKANA'],
                ['label' => 'SAKANA', 'label_mm' => 'ဆကန', 'value' => 'SAKANA'],
                ['label' => 'PABATA', 'label_mm' => 'ပဘတ', 'value' => 'PABATA'],
                ['label' => 'PAZATA', 'label_mm' => 'ပဇတ', 'value' => 'PAZATA'],
                ['label' => 'AHSANA', 'label_mm' => 'အစန', 'value' => 'AHSANA'],
                ['label' => 'AHLANA', 'label_mm' => 'အလန', 'value' => 'AHLANA'],
                ['label' => 'KAMANA', 'label_mm' => 'ကမန', 'value' => 'KAMANA'],
                ['label' => 'KATANA', 'label_mm' => 'ကတန', 'value' => 'KATANA'],
                ['label' => 'TATAHTA', 'label_mm' => 'တတထ', 'value' => 'TATAHTA'],
            ],

            '13' => [
                ['label' => 'PANGLONG',    'label_mm' => 'ပလန',   'value' => 'PANGLONG'],
                ['label' => 'MATATA',      'label_mm' => 'မတတ',   'value' => 'MATATA'],
                ['label' => 'MAYANA',      'label_mm' => 'မရန',   'value' => 'MAYANA'],
                ['label' => 'NAPHANA',     'label_mm' => 'နဖန',   'value' => 'NAPHANA'],
                ['label' => 'MAYANA',      'label_mm' => 'မယန',   'value' => 'MAYANA'], 
                ['label' => 'PHAKHANA',    'label_mm' => 'ဖခန',   'value' => 'PHAKHANA'],
                ['label' => 'KALADA',      'label_mm' => 'ကလဒ',   'value' => 'KALADA'],
                ['label' => 'KATALA',      'label_mm' => 'ကတလ',   'value' => 'KATALA'],
                ['label' => 'MASATA',      'label_mm' => 'မစတ',   'value' => 'MASATA'],
                ['label' => 'MAPHANA',     'label_mm' => 'မဖန',   'value' => 'MAPHANA'],
                ['label' => 'TALANA',      'label_mm' => 'တလန',   'value' => 'TALANA'],
                ['label' => 'MAMANA',      'label_mm' => 'မမန',   'value' => 'MAMANA'],
                ['label' => 'KHAYAHA',     'label_mm' => 'ခရဟ',   'value' => 'KHAYAHA'],
                ['label' => 'PAYANA',      'label_mm' => 'တခလ',   'value' => 'PAYANA'],
                ['label' => 'MAHTATA',     'label_mm' => 'မထတ',   'value' => 'MAHTATA'],
                ['label' => 'MAKHATA',     'label_mm' => 'မခတ',   'value' => 'MAKHATA'],
                ['label' => 'AHPANA',      'label_mm' => 'အပန',   'value' => 'AHPANA'],
                ['label' => 'AHTHAYA',     'label_mm' => 'အသယ',   'value' => 'AHTHAYA'],
                ['label' => 'HAHANA',      'label_mm' => 'ဟဟန',   'value' => 'HAHANA'],
                ['label' => 'KALANA',      'label_mm' => 'ကလန',   'value' => 'KALANA'],
                ['label' => 'MAPAHTA',     'label_mm' => 'မပထ',   'value' => 'MAPAHTA'],
                ['label' => 'KATATA',      'label_mm' => 'ကတတ',   'value' => 'KATATA'],
                ['label' => 'YASANA',      'label_mm' => 'ရစန',   'value' => 'YASANA'],
                ['label' => 'MASANA',      'label_mm' => 'မဆန',   'value' => 'MASANA'],
                ['label' => 'MATANA',      'label_mm' => 'မတန',   'value' => 'MATANA'],
                ['label' => 'MAMANA',      'label_mm' => 'မမန',   'value' => 'MAMANA'],  
                ['label' => 'MARATA',      'label_mm' => 'မရတ',   'value' => 'MARATA'],
                ['label' => 'YANYANA',     'label_mm' => 'ရညန',   'value' => 'YANYANA'],
                ['label' => 'NATANA',      'label_mm' => 'နတန',   'value' => 'NATANA'],
                ['label' => 'KHALANA',     'label_mm' => 'ခလန',   'value' => 'KHALANA'],
                ['label' => 'MAHTANA',     'label_mm' => 'မထန',   'value' => 'MAHTANA'],   
                ['label' => 'PALAHTA',     'label_mm' => 'ပလထ',   'value' => 'PALAHTA'],
                ['label' => 'TATANA',      'label_mm' => 'တတန',   'value' => 'TATANA'],  
                ['label' => 'MAYAHTA',     'label_mm' => 'မယထ',   'value' => 'MAYAHTA'],  
                ['label' => 'MAKAHTA',     'label_mm' => 'မကထ',   'value' => 'MAKAHTA'], 
                ['label' => 'KALATA',      'label_mm' => 'ကလတ',   'value' => 'KALATA'], 
                ['label' => 'LAKANA',      'label_mm' => 'လကန',   'value' => 'LAKANA'],  
                ['label' => 'TAKHALA',     'label_mm' => 'တခလ',   'value' => 'TAKHALA'], 
                ['label' => 'KAKHANA',     'label_mm' => 'ကခန',   'value' => 'KAKHANA'],  
                ['label' => 'MAKANA',      'label_mm' => 'မကန',   'value' => 'MAKANA'],   
                ['label' => 'KATHANA',     'label_mm' => 'ကသန',   'value' => 'KATHANA'],  
                ['label' => 'HAMANA',      'label_mm' => 'ဟမန',   'value' => 'HAMANA'],  
                ['label' => 'MAKATA',      'label_mm' => 'မကတ',   'value' => 'MAKATA'],   
                ['label' => 'NAHSANA',     'label_mm' => 'နဆန',   'value' => 'NAHSANA'],    
                ['label' => 'PATAYA',      'label_mm' => 'ပတယ',   'value' => 'PATAYA'],    
                ['label' => 'LAKHANA',     'label_mm' => 'လခန',   'value' => 'LAKHANA'],   
                ['label' => 'NAKHANA',     'label_mm' => 'နခန',   'value' => 'NAKHANA'],  
                ['label' => 'MAMAHTA',     'label_mm' => 'မမထ',   'value' => 'MAMAHTA'],  
                ['label' => 'MAYATA',      'label_mm' => 'မယတ',   'value' => 'MAYATA'],  
                ['label' => 'HAPATA',      'label_mm' => 'ဟပတ',   'value' => 'HAPATA'],   
                ['label' => 'PALATA',      'label_mm' => 'ပလတ',   'value' => 'PALATA'],   
                ['label' => 'PAWANA',      'label_mm' => 'ပဝန',   'value' => 'PAWANA'], 
                ['label' => 'KATANA',      'label_mm' => 'ကတန',   'value' => 'KATANA'],   
                ['label' => 'MAKHANA',     'label_mm' => 'မခန',   'value' => 'MAKHANA'],   
                ['label' => 'MALANA',      'label_mm' => 'မလန',   'value' => 'MALANA'],   
                ['label' => 'THAPANA',     'label_mm' => 'သပန',   'value' => 'THAPANA'],   
                ['label' => 'KAMANA',      'label_mm' => 'ကမန',   'value' => 'KAMANA'],  
                ['label' => 'MABANA',      'label_mm' => 'မဘန',   'value' => 'MABANA'],  
                ['label' => 'MALATA',      'label_mm' => 'မလတ',   'value' => 'MALATA'],   
                ['label' => 'MANGANA',     'label_mm' => 'မငန',   'value' => 'MANGANA'],  
                ['label' => 'MAMATA',      'label_mm' => 'မမတ',   'value' => 'MAMATA'],  
                ['label' => 'NAMATA',      'label_mm' => 'နမတ',   'value' => 'NAMATA'],    
                ['label' => 'NAKHATA',     'label_mm' => 'နခတ',   'value' => 'NAKHATA'],  
                ['label' => 'LAYANA',      'label_mm' => 'လရန',   'value' => 'LAYANA'],   
                ['label' => 'TAYANA',      'label_mm' => 'တယန',   'value' => 'TAYANA'],   
                ['label' => 'THANANA',     'label_mm' => 'သနန',   'value' => 'THANANA'],  
                ['label' => 'KAKANA',      'label_mm' => 'ကကန',   'value' => 'KAKANA'],    
                ['label' => 'LAKHATA',     'label_mm' => 'လခတ',   'value' => 'LAKHATA'],   
                ['label' => 'MAPANA',      'label_mm' => 'မပန',   'value' => 'MAPANA'],    
                ['label' => 'MANANA',      'label_mm' => 'မနန',   'value' => 'MANANA'],   
                ['label' => 'KAHANA',      'label_mm' => 'ကဟန',   'value' => 'KAHANA'],   
                ['label' => 'LALANA',      'label_mm' => 'လလန',   'value' => 'LALANA'],   
                ['label' => 'MANATA',      'label_mm' => 'မနန',   'value' => 'MANATA'],   
                ['label' => 'MAKHANA',     'label_mm' => 'မခန',   'value' => 'MAKHANA'],  
                ['label' => 'MAPHATA',     'label_mm' => 'မဖတ',   'value' => 'MAPHATA'],  
                ['label' => 'MAKHANA',     'label_mm' => 'မခန',   'value' => 'MAKHANA'],  
                ['label' => 'NASANA',      'label_mm' => 'နစန',   'value' => 'NASANA'],  
                ['label' => 'MAMANA',      'label_mm' => 'မမန',   'value' => 'MAMANA'],    
                ['label' => 'PASANA',      'label_mm' => 'ပဆန',   'value' => 'PASANA'],  
                ['label' => 'MAPATA',      'label_mm' => 'မပတ',   'value' => 'MAPATA'],   
                ['label' => 'PAPAKA',      'label_mm' => 'ပပက',   'value' => 'PAPAKA'],    
                ['label' => 'MAHAYA',      'label_mm' => 'မဟရ',   'value' => 'MAHAYA'],    
                ['label' => 'MASATA',      'label_mm' => 'မဆတ',   'value' => 'MASATA'],   
                ['label' => 'PASATA',      'label_mm' => 'ပဆတ',   'value' => 'PASATA'],   
                ['label' => 'TAMANYA',     'label_mm' => 'တမည',   'value' => 'TAMANYA'],   
                ['label' => 'KALAHTA',     'label_mm' => 'ကလထ',   'value' => 'KALAHTA'],   
                ['label' => 'HAPANA',      'label_mm' => 'ဟပန',   'value' => 'HAPANA'],     
                ['label' => 'SASANA',      'label_mm' => 'ဆဆန',   'value' => 'SASANA'],    
                ['label' => 'AHTANA',      'label_mm' => 'အတန',   'value' => 'AHTANA'],  
                ['label' => 'NATAYA',      'label_mm' => 'နတရ',   'value' => 'NATAYA'],  
                ['label' => 'NYAYANA',     'label_mm' => 'ညရန',   'value' => 'NYAYANA'], 
                ['label' => 'PALATA',      'label_mm' => 'ပလန',   'value' => 'PALATA'],   
                ['label' => 'TAKANA',      'label_mm' => 'တကန',   'value' => 'TAKANA'],   
                ['label' => 'YANGANA',     'label_mm' => 'ရငန',   'value' => 'YANGANA'],   
                ['label' => 'MAYANA',      'label_mm' => 'မရန',   'value' => 'MAYANA'],    
            ],

            '14' => [
                ['label' => 'KAPANA', 'label_mm' => 'ကပန', 'value' => 'KYONPYAW'],
                ['label' => 'PHAPANA', 'label_mm' => 'ဖပန', 'value' => 'PHYAPON'],
                ['label' => 'PATANA', 'label_mm' => 'ပတန', 'value' => 'PANTANAW'],
                ['label' => 'AHMANA', 'label_mm' => 'အမန', 'value' => 'EINME'],
                ['label' => 'MAAHNA', 'label_mm' => 'မအန', 'value' => 'MYANAUNG'],
                ['label' => 'NYATANA', 'label_mm' => 'ညတန', 'value' => 'NYAUNGDON'],
                ['label' => 'HAKAKA', 'label_mm' => 'ဟကက', 'value' => 'HAINGGYIKYUN'],
                ['label' => 'YATHAYA', 'label_mm' => 'ယသရ', 'value' => 'SHWETHAUNGYAN'],
                ['label' => 'NGATHAKHA', 'label_mm' => 'ငသခ', 'value' => 'NGATHAINGCHAUNG'],
                ['label' => 'PATHAYA', 'label_mm' => 'ပသရ', 'value' => 'PATHEIN-EAST'],
                ['label' => 'THAPANA', 'label_mm' => 'သပန', 'value' => 'THAPAUNG'],
                ['label' => 'BAKALA', 'label_mm' => 'ဘကလ', 'value' => 'BOGALE'],
                ['label' => 'DANAPHA', 'label_mm' => 'ဓနဖ', 'value' => 'DANUBYU'],
                ['label' => 'PASALA', 'label_mm' => 'ပစလ', 'value' => 'PYINSALU'],
                ['label' => 'LAMANA', 'label_mm' => 'လမန', 'value' => 'LAYMYETHNA'],
                ['label' => 'AHGAPA', 'label_mm' => 'အဂပ', 'value' => 'INGAPU'],
                ['label' => 'NGAYAKA', 'label_mm' => 'ငရက', 'value' => 'NGAYOKAUNG'],
                ['label' => 'NGASANA', 'label_mm' => 'ငဆန', 'value' => 'NGWEHSAUNG'],
                ['label' => 'LAPATA', 'label_mm' => 'လပတ', 'value' => 'LABUTTA'],
                ['label' => 'MAMANA', 'label_mm' => 'မမန', 'value' => 'MYAUNGMYA'],
                ['label' => 'PATHAAH', 'label_mm' => 'ပသအ', 'value' => 'PATHEIN'],
                ['label' => 'PATHANA', 'label_mm' => 'ပသန', 'value' => 'PA THEIN'],
                ['label' => 'MAMAKA', 'label_mm' => 'မမက', 'value' => 'MAWLAMYINEGYUN'],
                ['label' => 'KAKHANA', 'label_mm' => 'ကခန', 'value' => 'KYANGIN'],
                ['label' => 'KAKAHTA', 'label_mm' => 'ကကထ', 'value' => 'KANGYIDAUNT'],
                ['label' => 'KALANA', 'label_mm' => 'ကလန', 'value' => 'KYAIKLATT'],
                ['label' => 'NGAPATA', 'label_mm' => 'ငပတ', 'value' => 'NGAPUTAW'],
                ['label' => 'MAAHPA', 'label_mm' => 'မအပ', 'value' => 'MAUBIN'],
                ['label' => 'AHMATA', 'label_mm' => 'အမတ', 'value' => 'AHMAR'],
                ['label' => 'HATHATA', 'label_mm' => 'ဟသတ', 'value' => 'HINTHADA'],
                ['label' => 'YAKANA', 'label_mm' => 'ရကန', 'value' => 'YEKYI'],
                ['label' => 'KAKANA', 'label_mm' => 'ကကန', 'value' => 'KYAUNGON'],
                ['label' => 'DADAYA', 'label_mm' => 'ဒဒရ', 'value' => 'DAYDAYE'],
                ['label' => 'WAKHAMA', 'label_mm' => 'ဝခမ', 'value' => 'WAKEMA'],
                ['label' => 'ZALANA', 'label_mm' => 'ဇလန', 'value' => 'ZALUN']
            ],

            '9*' => [
                ['label' => 'ZABATHA', 'label_mm' => 'ဇဗသ', 'value' => 'ZABUTHIRI'],
                ['label' => 'AUTATHA', 'label_mm' => 'ဥတသ', 'value' => 'OTTARATHIRI'],
                ['label' => 'PABATHA', 'label_mm' => 'ပဗသ', 'value' => 'POBBATHIRI'],
                ['label' => 'TAKANA', 'label_mm' => 'တကန', 'value' => 'TATKON'],
                ['label' => 'DAKHATHA', 'label_mm' => 'ဒခသ', 'value' => 'DEKKHINATHIRI'],
                ['label' => 'LAWANA', 'label_mm' => 'လဝန', 'value' => 'LEWE'],
                ['label' => 'PAMANA', 'label_mm' => 'ပမန', 'value' => 'PYINMANA'],
                ['label' => 'ZAYATHA', 'label_mm' => 'ဇယသ', 'value' => 'ZEYARTHIRI']
            ],


        ],
        'citizens' => [
            ['label' => '(နိုင်)', 'value' => 'နိုင်'],
            ['label' => '(ဧည့်)', 'value' => 'ဧည့်'],
            ['label' => '(ပြု)', 'value' => 'ပြု']
        ],
        'genders' => [
            ['label' => 'Male', 'value' => 'Male'],
            ['label' => 'Female', 'value' => 'Female'],
        ],
        'job_types' => [
            ['label' => 'Full Time', 'value' => 'full'],
            ['label' => 'Part Time', 'value' => 'part'],
        ],
        'paginate_per_page' => 10,
    ];

